### ISSUE TITLE
[建议]希望减少条漫阅读中的误触

### ISSUE THREAD

**Issue by Maolon** [crowforkotlin/PasteMangaX#101]
在翻阅条漫的时候会经常进行如下手势
上下拖拽(drag)
上下快速甩动(fling)
有时候会被识别为单次点击从而触发隐藏的header和底部的功能栏显示
这个误操作会经常被触发
可否通过
1. 增加识别threshold
或者
2. 将此功能从操作热区移除(也就是仅当用户点击屏幕底部和顶部时才显示)
来解决这个问题？

**Comment by crowforkotlin** [comment]
后续会跟进、大概率是加到热区，减少误触也会看的目前先暂时用音量键锁定吧
