### ISSUE TITLE
请问可否加入“关闭翻页动画效果”的选项

### ISSUE THREAD

**Issue by goodmorning-hwt** [crowforkotlin/pastemangax#124]
电子书上使用app的话翻页有动画效果会有点难受

**Comment by crowforkotlin** [comment]
可以的，下个版本在阅读器设置中添加此功能

**Comment by goodmorning-hwt** [comment]
> 可以的，下个版本在阅读器设置中添加此功能

感激不尽捏

**Comment by MrPinku** [comment]
借问一下现版本是没有点击翻页的功能？

**Comment by crowforkotlin** [comment]
> 借问一下现在版本是没有点击翻页功能吗？

现版本尚未实现，但是目前已经搞定了，后续会尽快发布

**Comment by MrPinku** [comment]
> > 借问一下现在版本是没有点击翻页功能吗？
> 
> 现版本尚未实现，但是目前已经搞定了，后续会尽快发布

感谢，期待~
