### ISSUE TITLE
[bug]经典和条漫模式下无法正确加载部分长图韩漫

### ISSUE THREAD

**Issue by zbc258** [crowforkotlin/pastemangax#125]
如题，显示模式设置为经典或条漫时，没有正确按宽度缩放图片，导致部分长图形式的漫画无法正确显示，图与图之间出现大量黑边，部分日漫大图也有这个问题。而在上下和左右翻页模式的话很多漫画图片无法正确居中，也是周围有黑边，需要双击一下才能居中，希望可以改善一下自动缩放。

**Comment by crowforkotlin** [comment]
此问题已经在下个版本进度中被修复完成了，请等待下个版本的发行
