### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by Gonzomio** [crowforkotlin/PasteMangaX#67]
APP做得很不错，尤其界面设计得很漂亮，但缺少一些较基础的功能。
希望能删除浏览记录，包括选择删除和一键清除。
漫画下载和收藏漫画的更新提示功能（比如在收藏界面的漫画封面上加个小红点，或者文字提醒）。
关于浏览记录，首先现在的版本是不支持记录看到多少页的，然后只能记录到上回退出漫画浏览界面的话数。比如一部漫画我看到第5话，然后退出返回到漫画详情页，软件就只记录到第5话。下次我看到第10话了，但中途被打断（比如电话或者闹钟），返回漫画浏览界面的时候，它又会跳回到第5话的开头。如果直接退出软件，下次再打开来看，也是这种情况。
希望能修复改善

**Comment by crowforkotlin** [comment]
感谢您的建议，后续持续跟进
