### ISSUE TITLE
部分漫画缺失单行本的内容

### ISSUE THREAD

**Issue by RX93CN** [crowforkotlin/PasteMangaX#74]
**Smartphone (please complete the following information):**
 - Device: [e.g. xiaomi12]
 - OS: [e.g. MIUI 13]
 - AppVersion [e.g. 1.3.1]

**Describe the bug**
 正常的页面里可以看到单行本有几卷，现版本部分漫画不显示单行本内容

**To Reproduce**

**Expected behavior**
A clear and concise description of what you **expected** to happen.

**Screenshots**

**Comment by crowforkotlin** [comment]
请问是哪个漫画？ 请举个例子我才好复现

**Comment by RX93CN** [comment]
> 请问是哪个漫画？ 请举个例子我才好复现

![Screenshot_2023-12-28-16-57-59-909_com crow copymanga](https://github.com/crowforkotlin/CopyMangaX/assets/110704357/b97e2645-61d7-4bb7-896e-44a09928f7bd)
![Screenshot_2023-12-28-16-59-16-190_eu kanade tachiyomi j2k](https://github.com/crowforkotlin/CopyMangaX/assets/110704357/36f82ebc-5f69-4661-a207-2560a6487ba2)
下面这张是在tachij2k上的同一本漫画，可以看见有单行本的部分

**Comment by crowforkotlin** [comment]
这个啊，这个要单独弄个单行本的选项，没做而已，后期增加
